---
hero_image: images/countdown-timer.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Countdown timer (काउंटडाउन टाइमर)
description: Raspberry Pi के लिए Sense HAT पर काउंटडाउन टाइमर प्रदर्शित करें।
original_url: https://codeclubprojects.org/en-GB/sense-hat/countdown-timer
interests: ''
technologies: sense-hat
site_areas: प्रोजेक्ट
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: पाठ की उलटी गिनती
  - 
    title: 'चुनौती: कोई दूसरा रंग'
  - 
    title: डॉट टाइमर बनाना
  - 
    title: 'चुनौती: टाइमर गेम'
